'use strict'
const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('diary', {
  getData: () => ipcRenderer.invoke('diary:get-data'),
  addNote: (note) => ipcRenderer.invoke('diary:add-note', note),
  getRepoLinks: () => ipcRenderer.invoke('diary:get-repo-links'),
  getSpriteSources: () => ipcRenderer.invoke('diary:get-sprite-sources'),
  openExternal: (url) => ipcRenderer.send('diary:open-external', url),
  getCards: () => ipcRenderer.invoke('diary:get-cards'),
  createCard: (card) => ipcRenderer.invoke('diary:create-card', card),
  updateCard: (id, changes) => ipcRenderer.invoke('diary:update-card', id, changes),
  deleteCard: (id) => ipcRenderer.invoke('diary:delete-card', id),
  getShares: () => ipcRenderer.invoke('diary:get-shares'),
  createShare: (texto) => ipcRenderer.invoke('diary:create-share', texto),
  createShareFile: (filePath, texto) => ipcRenderer.invoke('diary:create-share-file', filePath, texto),
  deleteShare: (id) => ipcRenderer.invoke('diary:delete-share', id),
  getShareFile: (id) => ipcRenderer.invoke('diary:get-share-file', id),
  pickShareFile: () => ipcRenderer.invoke('diary:pick-share-file'),
  saveShareFile: (id, suggestedName) => ipcRenderer.invoke('diary:save-share-file', id, suggestedName),
  getTasks: (proyectoId) => ipcRenderer.invoke('diary:get-tasks', proyectoId),
  getProjects: () => ipcRenderer.invoke('diary:get-projects'),
  createProject: (nombre) => ipcRenderer.invoke('diary:create-project', nombre),
  deleteProject: (id) => ipcRenderer.invoke('diary:delete-project', id),
  getTask: (id) => ipcRenderer.invoke('diary:get-task', id),
  createTask: (task) => ipcRenderer.invoke('diary:create-task', task),
  updateTask: (id, changes) => ipcRenderer.invoke('diary:update-task', id, changes),
  deleteTask: (id) => ipcRenderer.invoke('diary:delete-task', id),
  getComments: (taskId) => ipcRenderer.invoke('diary:get-comments', taskId),
  addComment: (taskId, texto) => ipcRenderer.invoke('diary:add-comment', taskId, texto),
  deleteComment: (taskId, commentId) => ipcRenderer.invoke('diary:delete-comment', taskId, commentId),
  pathForFile: (file) => webUtils.getPathForFile(file),
  getFlow: () => ipcRenderer.invoke('diary:get-flow'),
  saveFlow: (flow) => ipcRenderer.invoke('diary:save-flow', flow)
})
